const { Router } = require("express")

const router = Router()
const jwt = require('jsonwebtoken')
const mongoose = require('mongoose')
const dotenv = require('dotenv')
const cors = require('cors')

dotenv.config()

//import the authentication middleware
const Authmiddleware = require("../Authentication/auth")

const {UserModel,JournalModel} = require("../Database/db")


router.post('/addjournal',Authmiddleware,async function(req,res){

  //if auth was succesfull username will be given forward
  const username = req.username

  const description = req.body.description
  const bookmark = req.body.bookmark
  const date = req.body.date

  let userfound = await UserModel.findOne({username: username})

  //giving a unique special userid as discussed in db.js auto generated by mongodb
  let userId = userfound._id
  console.log(userId)

  if(description && date){
    try{
      await JournalModel.create({
        description: description,
        bookmark: bookmark,
        date: date,
        userId: userId
      })

      res.status(200).json({
        message: "Journal Succesfully added"
      })
    }
    catch(e){
      res.status(403).json({
        message: "some error occured while adding the journal",
        error: e
      })
    }
  }

  else{
    res.status(302).json({
      message: "Please enter all the details"
    })
  }



})







module.exports = router